New profile page
LazyAfternoons/io-app pull request #1
Opened 2023-03-31 12:24 UTC by LazyAfternoons

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2023-04-03 13:06 UTC, shadowsheep1 requested changes
Not all my comments needs a modification. Some of them are only put here to trigger an useful discussion.

2023-04-03 15:40 UTC, LazyAfternoons commented on ts/screens/profile/newProfileScreen.tsx
> +  const renderMask = () =>
Fixed in [f3e3c0c](https://github.com/LazyAfternoons/io-app/pull/1/commits/f3e3c0c9f65b53a6047495ef3b28699893f00d63), thanks.

2023-04-03 15:40 UTC, LazyAfternoons commented on ts/screens/profile/newProfileScreen.tsx
> +      {renderMask()}
Fixed in [f3e3c0c](https://github.com/LazyAfternoons/io-app/pull/1/commits/f3e3c0c9f65b53a6047495ef3b28699893f00d63), thanks.

2023-04-03 15:40 UTC, LazyAfternoons commented on ts/screens/profile/newProfileScreen.tsx
> +  const renderLoadingView = () => (
Fixed in [f3e3c0c](https://github.com/LazyAfternoons/io-app/pull/1/commits/f3e3c0c9f65b53a6047495ef3b28699893f00d63), thanks.

2023-04-03 15:40 UTC, LazyAfternoons commented on ts/screens/profile/newProfileScreen.tsx
> +  const renderErrorView = () => (
Fixed in [f3e3c0c](https://github.com/LazyAfternoons/io-app/pull/1/commits/f3e3c0c9f65b53a6047495ef3b28699893f00d63), thanks.

2023-04-03 15:41 UTC, LazyAfternoons commented on ts/navigation/TabNavigator.tsx
> +import NewProfileScreen from "../screens/profile/newProfileScreen";
Ops, this one slipped away, thanks. Fixed in[5726e85](https://github.com/LazyAfternoons/io-app/pull/1/commits/5726e85a3b76168ba5096b087d46fae7b575bf43).

2023-04-03 15:42 UTC, LazyAfternoons commented on ts/components/screens/ListItemComponent.tsx
> +import { SvgProps } from "react-native-svg";
I absolutely agree with you on this one, however, the onboarding path references tests in the very last point so I decided to implement all the tests in the last PR.

2023-04-03 15:42 UTC, LazyAfternoons commented on ts/navigation/AppStackNavigator.tsx
> +            [ROUTES.NEW_PROFILE_MAIN]: "new-profile"
Indeed, fixed in [007f977](https://github.com/LazyAfternoons/io-app/pull/1/commits/007f97705284fb015cd746253374068dddfdd379).

2023-04-03 15:43 UTC, LazyAfternoons commented on ts/navigation/params/MainTabParamsList.ts
> +  [ROUTES.NEW_PROFILE_MAIN]: undefined;
Fixed in [007f977](https://github.com/LazyAfternoons/io-app/pull/1/commits/007f97705284fb015cd746253374068dddfdd379), thanks.

2023-04-03 15:43 UTC, LazyAfternoons commented on ts/navigation/routes.ts
> +  NEW_PROFILE_MAIN: "NEW_PROFILE_MAIN",
Indeed, fixed in [007f977](https://github.com/LazyAfternoons/io-app/pull/1/commits/007f97705284fb015cd746253374068dddfdd379).

2023-04-03 16:17 UTC, LazyAfternoons commented on ts/screens/profile/newProfileScreen.tsx
> +  );
Absolutely, I replaced the "in house" components with `LoadingErrorComponent` in [5246bde](https://github.com/LazyAfternoons/io-app/pull/1/commits/5246bde969cf9c1888db945ac3a9fcc694eca204). I kept the wrappers though, that makes the fold more readable and avoids having to redefine them because in this case we are mapping the same components multiple times.

2023-04-03 16:48 UTC, LazyAfternoons commented on ts/sagas/startup.ts
> +
Yes, that's correct. I decided to split them and use the `NewProfile` data in the `NewProfileScreen` while keeping the existing logic.

2023-04-03 16:53 UTC, LazyAfternoons commented on ts/store/reducers/types.ts
> +  newProfile: NewProfileState;
It is as I did not find any reason to persist the new state as it's only used for displaying data into the profile screen. The "old" business logic around the profile data stays the same and takes care of that.

2023-04-04 10:31 UTC, shadowsheep1 commented on ts/components/screens/ListItemComponent.tsx
> +import { SvgProps } from "react-native-svg";
Okay, then. But In this case shouldn't be better to use Components composability (write a new component by composing the old one with new UI views) instead of changing a legacy one? Anyway, for the purpose of this PR we could leave it the way it is.

2023-04-04 10:36 UTC, shadowsheep1 approved these changes
LGTM 🚀

2023-04-04 10:47 UTC, LazyAfternoons commented on ts/components/screens/ListItemComponent.tsx
> +import { SvgProps } from "react-native-svg";
I think that might be a better approach, yes.

2023-04-04 10:48 UTC, merged